# Generated by Django 3.2.8 on 2021-10-19 17:05

from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published post')], default=press.models.PostStatus['DRAFT'], max_length=32),
        ),
    ]
