# Generated by Django 3.2.8 on 2021-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20211020_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
